# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-17 17:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 4, 17, 17, 11, 2, 903043, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
